#!/usr/bin/env bash
#this script this for installing and confi HAProxy
#update the system

sudo apt-get -y upgrade 

#dedicated PPA with the following command:
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.0

#install the HAProxy 
sudo apt-get -y install haproxy=2.0.\*

echo -e \
"\nlisten load_balancer
\tbind :80
\tmode http
\tstats enable
\tstats uri /haproxy?stats
\tbalance roundrobin
\tserver 516696-web-01 54.152.134.222:80 check
\tserver 516696-web-02 35.168.2.251:80 check" \
    >> /etc/haproxy/haproxy.cfg
service haproxy restart


