#!/usr/bin/env bash
# this script check the stauts of th file school

if [ -e school ]
then
	echo "school file exists"
if [ -s school ]
then
	echo "school file is not empty"
else
	echo "school file is empty"
fi
if [ -f school ]
then
	echo "school file is a regular file"
fi
else
	echo "school file dose not exist"
fi

